### ISSUE TITLE
Beacon API info objects debris

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-framework-v2#10]
Continuing the discussion on https://github.com/ga4gh-beacon/specification-v2/issues/61.

As mentioned in the thread above:

`/service-info` is the mandatory endpoint for GA4GH products and must return the service-info schema.

If we keep it as the only informational endpoint (which not true anymore in the Beacon Framework v2), then we'll break the rule of Beacon not having a hard dependency on any external schema or specification which blocks us for evolving the concept if we need it.
Hence, we need another endpoint that uses a Beacon v2 Model schema. Originally this was the role of `/info`. 
However in some point in time it was decided that `/` should play that role.
As `/` is not explicit enough, a bit misleading and not retrocompatible, we kept `/info` also.
Add that time we didn't had the alternative schemas support yet, hence we add the `model` parameter to allow using the `/info` endpoint but getting a 'service-info' payload wrapped inside a Beacon response. Hence we keep coherence between responses.

Later, we add the idea of alternative schemas through the `requestedSchemas` parameter, and `model `became obsolete. I'll double if it is dragged to the Framework.

I still strongly believe that API and UI should not be mixed in the spec and that two separated base paths should be used for that purpose.

**Comment by mbaudis** [comment]
I, personally, hate `/` for an info etc. It should either direct to a UI, or be the default for accepting a request. No idea about the conventions.
