### ISSUE TITLE
duplicated "operationId": "getBeaconInfoRoot"

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-framework-v2#11]
There are two "getBeaconInfoRoot" operations defined in the endpoints.json (for the "/" and for the "/info").
According the OpenAPI 3.0 "The id MUST be unique among all operations described in the API"

Cheers,

Dmitry

**Comment by jrambla** [comment]
Solved in commit 741e2e5
This was copy & paste issue ;-)
