### ISSUE TITLE
Schemas should be PascalCased

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#14]
... n/c

**Comment by jrambla** [comment]
Could you be more precise, please?

**Comment by mbaudis** [comment]
Well, schemas, classes... which have their own properties should be UpperCased (PascalCased), in contrast to properties themselves. There is no _strict_ requirement to do so, but this is in line with much of JSON Schema usage & Schema.org conventions. AND has been the practice, so far, e.g. in the Beacon [components](https://github.com/ga4gh-beacon/specification-v2/blob/a9fb4c9e293de2d9ea3fc65831d0e8d0c92bdfa6/beacon.yaml#L1857).

So flipping this now to "everything is camelCased" is breaking a lot. I do not _necessarily_ have a problem with that, but it is a bit like "these were my editor's settings, let's just go ahead" with it, at least without a **bold faced** "we accept camels, only" :-)

Also: There _is_ some soft convention to snake_case JSON data responses for web APIs - and Beacon used this before. (I've lost some hours now refactoring my web interface to accept cC - don't mention it - alas...).

Summary: Clear casing guidance needed.

**Comment by jrambla** [comment]
True. 
camel/Pascal case is the convention we aim to follow for properties vs. components and snakecase for endpoints.
Have you spotted any place where we are breaking that convention?

**Comment by jrambla** [comment]
@mbaudis any place where we are breaking the convention?

**Comment by jrambla** [comment]
As no specific points/places has been pointed, I'm closing this issue. 
Please create a new one with any error you could spot.

**Comment by mbaudis** [comment]
@jrambla `BasicElement` would be the class name. If you have a JSON document `basicElement.json` with its properties etc. it is AFIK not clear that it defines the `BasicElement` class, which should also be used in references.

I'm actually not sure if defining  `name: BasicElement` property inside `basicElement.json` would help; but "if it's a document with properties than it is a class and the file should be PC, if it has definitions than there are additional `PascalCased` classes, too" is AFAIK the proper way?!

But: This was all very nice and clear at some point before.
