### ISSUE TITLE
datasetIds instead of Datasets in example

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#2]
Should be `datasetIds` instead of `Datasets` in example?

https://github.com/ga4gh-beacon/beacon-framework-v2/blob/385936854db1741d367b3a61ecdd62dc98d806f4/requests/examples/beaconRequestBody-MAX-example.json#L11

**Comment by jrambla** [comment]
That attribute is a fake example, as the "filters" section just below it.
It is probably misleading and we should update to make it more clear that is not a suggestion of how a list of Dataset Ids should be populated.
Actually the option to select specific datasets has slipped down in the framework, as it is expected to be part of every model.

**Comment by jrambla** [comment]
I've updated the example in commit [d43df44dc5532a1fd7b945253c1d1ad903b2e1e9]
