### ISSUE TITLE
Refactoring responses

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#21]
The current responses are complex and a bit inconsistent, since:

* a [`BeaconCoreResponse`](https://github.com/ga4gh-beacon/beacon-framework-v2/blob/main/responses/beaconCoreResponse.json) allows two different contents, to fulfil the option for a Boolean-only response while also providing a slightly more useful count response
* the complete `BeaconCoreResponse` is used as part of the [`BeaconResultsetsResponse`](https://github.com/ga4gh-beacon/beacon-framework-v2/blob/main/responses/beaconResultsetsResponse.json) instead of using the relevant sections directly

The PR #20 splits the `BeaconCoreResponse` in separate Boolean and Counts responses, and refactors the `BeaconResultsetsResponse` to use the sections instead of a mix of same-level responses.

**Comment by mbaudis** [comment]
NB: Any of the `BeaconBooleanResponse` or `BeaconCountResponse` could also be called `BeaconCoreResponse` :-)

**Comment by jrambla** [comment]
I like the idea of splitting them to emphasize the options that a Beacon implementer has.
I've commented the PR.

**Comment by jrambla** [comment]
I'm closing this as PR #20 has been approved and merged.
