### ISSUE TITLE
beaconNonEmptyResultset requirement for "results" doesn't allow boolean and counts only responses?

### ISSUE THREAD

**Issue by colinveal** [ga4gh-beacon/beacon-framework-v2#24]
the current schema for resultsets requires a "results" with a 'minItems': 1, however for our use case we would like to return exists and counts on a per resultset basis without including individual results. Would it be a problem to remove this requirement?

**Comment by mbaudis** [comment]
+1; results should be optional and also allow empty lists (for match 0 but expected results parameter).

**Comment by jrambla** [comment]
Oh!, I see.
My original assumption was that when using the beaconResultsetsResponse, there are details to return, but you are right: you can still would like to use beaconResultsetsResponse to provide boolean+count responses per result set.
I'll update it.
