### ISSUE TITLE
Missing full bodied examples

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/beacon-framework-v2#25]
There are a lot of small, partial examples which match up with the small schema chunks but can you make a set of examples which show the entire request/response body and all possible default properties/schemas? and importantly these should be in pure JSON, exactly as you would expect the request or response to be formed when being sent to/from a beacon implementation.

**Comment by mbaudis** [comment]
+1

**Comment by jrambla** [comment]
IMU, there should be examples for most of the whole documents too. 
I'm fine, if you suggest that, to move them into a separate folder for clarity.
Please, point the ones you are missing (note: some informational ones could have been added in the recent days)

**Comment by jrambla** [comment]
I'll consider this solved unless something pops out.
