### ISSUE TITLE
inconsistent use of '_' and '-' in endpoints

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/beacon-framework-v2#28]
`/filtering_terms`
`/entry_types`
(and I believe every other endpoint, including the model repo, made from 2+ words)

vs

`/service-info`

I'm guessing this is because `/service-info` is the required endpoint for GA4GH and not `/service_info` but standardising them would make a lot of sense (it would also limit the number of people implementing /service_info by mistake, like me).

I have no problems with following GA4GH and switching all endpoints to use hyphens instead of underscores, updating implementations to use hyphens instead of underscores shouldn't take very long.

**Comment by colinveal** [comment]
Yes I agree we should be consistent. However also bear in mind that some MVCs will not accept hyphens in function names.

**Comment by mbaudis** [comment]
Just FYI, the `service-info` is an external style/dependency. Otherwise, no use of kebab-case, AFAIK.

**Comment by laurenfromont** [comment]
I don't think I can modify the readme, not being an admin.

**Comment by jrambla** [comment]
Added to readme
