### ISSUE TITLE
Examples on how to represent filtering terms in the GET query URL

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-framework-v2#43]
Given that, for some time, we had only managed POST operations we haven't discussed in depth how to apply different filter types when used in the query string.
Should we provide examples of them?

**Comment by tb143** [comment]
Yes, we should provide examples.

The scout started off by considering GET requests and most of our filters discussions with partners used GET request examples, so we do have some already documented.

Where should we add in these examples?

**Comment by jrambla** [comment]
Wonderful!
I guess that we can add these examples to 3 different places (in order my preference):

1. The Filters Scout document (the natural place, out of the repos but could be linked there)
2. The README here (also natural, but not where the users would look at it)
3. The README in the Models (where more users will go, but in the topic is broader than the Beacon v2 Model, hence is not the appropriate part. We must put a link there that points to the place where the examples fit).

Best!

**Comment by mbaudis** [comment]
@tb143 I think the point `1.` by @jrambla above, obviously. But we already started the [implementations](https://github.com/ga4gh-beacon/implementations-v2) repo which IMO is a much cleaner place for having a readable documentation with [examples](https://github.com/ga4gh-beacon/implementations-v2/blob/main/progenetix-examples.md#individuals--query).

IMO we could have all this as part of a main RTD document (e.g. also adding examples in an "Appendix" section). There is a [stub of a doc here](https://beacon-schema-2.readthedocs.io/en/latest/) (not in the main org yet...).

Pinging @mrueda and @laurenfromont.

**Comment by mbaudis** [comment]
@tb143 @jrambla etc.: Again, bump for using the [implementations](https://github.com/ga4gh-beacon/implementations-v2) repo! The registry server cannot provide this kind of documentation - this is in parallel.

Alternative - moving this to a common documentation space, where then different core implementers add their examples? What is planned with the RTD documentation?
