### ISSUE TITLE
Clarification on filter terms for array attributes

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-framework-v2#44]
I'm expecting a confusion generated between the users looking at model and assuming that the Model is mirroring the underlying database schema. 
I'm falling in that trap time and again ;-)

For example, I've created a filter for a property that is an array ("aminoacidChanges" in "genomicVariation") and wondered which is the right operator for that. Of course "=" (and other operations) could be interpreted properly, but I've guessed if we need to add a couple of comments in the documentation:

1. Highlighting that the Model is not a mirror of the underlying repository _<< this could also go in other places of the overall documentation_
2. How the operators behave in an array context

Makes sense?

**Comment by mbaudis** [comment]
Has been superseded by documentation etc., IMO. Closing.
