### ISSUE TITLE
[Q] beaconMapSchema.json RelatedEndpoints 

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-framework-v2#45]
Hello,

In the beaconMapSchema.json schema Endpoint.endpoints defined as:
~~~json
"endpoints": {
  "description": "Optional. A list describing additional endpoints implemented by this Beacon instance for that entry type. Additional details on the endpoint parameters, supported HTTP verbs, etc. could be obtained by parsing the OpenAPI definition referenced in the `openAPIEndpointsDefinition` attribute.",
  "type": "object",
  "additionalProperties": {
    "$ref": "#/definitions/RelatedEndpoints"
  },
  "minProperties": 0
}
~~~
The description states about the list of additional endpoints, while the propery and ReatedEndpoints object are the objects.
The questions are:
1. Should "endpoints" property be defined as an array?
2. Should RelatedEndpoints be renamed to RelatedEndpoint (singular)?
3. What is a reason to use "additionalProperies" (not used for the array type (1), but anyway it is used for the restricting the additional properties, not defining concrete one).

Cheers,

Dmitry

**Comment by jrambla** [comment]
@redmitry I guess part of your questions are already answered discussed in #47, let me know if that is not the case.
For the question about "singular vs plural2, you are right, that should be singular.
Could you create a PR for it?
