### ISSUE TITLE
beaconConfigurationSchema.json no "type" : "object" specified in the EntryTypes

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-framework-v2#47]
Hello,

In the `beaconConfigurationSchema.json` schema:
~~~json
"properties": {
  "entryTypes": {
    "$ref": "#/definitions/EntryTypes"
  }
},
"definitions": {
  "EntryTypes": {
    "additionalProperties": {
      "type": "object",
      "$ref": "./entryTypeDefinition.json"
    },
  }
}
~~~
There is no **"type"** defined for the `EntryTypes` entry, thus something like "entryTypes": 6 is perfectly valid.

P.S. if I understand correctly the scheme something like:
~~~json
"entryTypes" : {
  "property1" : {
    "$ref": "./entryTypeDefinition.json"
  },
  "property2" : {
    "$ref": "./entryTypeDefinition.json"
  }
}
~~~
is expected.

Cheers,

Dmitry

**Comment by jrambla** [comment]
If I'm not mistaken the schema w/o properties and with a component in additional properties is the suggested way to create a dictionary (as "opposite" of an array) in Json Schema draft07.
This [thread ](https://stackoverflow.com/questions/27357861/dictionary-like-json-schema) shows an example of that approach or in Swagger [Dictionaries, HashMaps and Associative Arrays](https://swagger.io/docs/specification/data-models/dictionaries/)
Are we missing something?

**Comment by redmitry** [comment]
>schema w/o properties and with a component in additional properties is the suggested way to create a dictionary
Smart :-)
>Are we missing something?
Yes. `"type": "object"` :
~~~json
"EntryTypes": {
    "type": "object",
    "additionalProperties": {
~~~
Schemas without explicitly defined **type** are of **any** type.
In this case it can be any "string", "number", "array", etc.

**Comment by jrambla** [comment]
With the current schema defiinition (w/o the type) when I try something like
```
  "entryTypes": {
    "something": "something"
    },
```
I'm getting a validation error as 'Incorrect type. Expected "object"' 
So, or I'm  missing something, or the validator is incorrect, or it is not actually necessary to define the type.
What do you think?

**Comment by redmitry** [comment]
Probably the validator issue...
https://www.jsonschemavalidator.net/
~~~json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "entryTypes": {
      "$ref": "#/definitions/EntryTypes"
    }
  },
  "definitions": {
    "EntryTypes": {
      "additionalProperties": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        }
      },
      "minProperties": 1
    }
  },
  "required": ["entryTypes"],
  "additionalProperties": true
}
~~~
will validate:
~~~json
{
  "entryTypes" : 6
}
~~~
"EntryTypes" must have `"type": "object"` defined. Otherwise, it may be of any type. Having "additionalProperties" is interpreted by the specification as **IF** the 'type' is 'object' it MUST have at least one property ('minProperties': 1), but if it is other type, "additionalProperties" just ignored.

Dmitry

**Comment by jrambla** [comment]
I believe this was solved in a  commit
