### ISSUE TITLE
`basicElement.name` => `basicElement.label`?

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#50]
I don't understand the reason for using `name` instead of `label` in `basicElement`? 

https://github.com/ga4gh-beacon/beacon-framework-v2/blob/db6cf29837c07a2aa5a403d497c912b60ac36bcc/common/basicElement.json#L11

Using `name` is limiting in that a name is typically be thought of as an identifier with some semantic meaning. This

* potentially leads to conflicts with `id` (though the structure protects here a bit by making both required)
* discourages more complex labels (e.g. the longest NCIT label/name in our current cancer DX has 101 characters in 11 words...)
* an `id` / `label` combo is in line w/ the `OntologyTerm` class
* the mix of `id` / `name` with `id` / `label` is a bit confusing (for me)

If there isn't a strong reason / convention for using `name` here I would suggest to switch to `label`.

**Comment by redmitry** [comment]
I think the explanation can be inferred from the example:
https://github.com/ga4gh-beacon/beacon-framework-v2/blob/main/configuration/examples/entriesCollectionDefinition_example.json
~~~json
{
  "$schema": "../entryTypeDefinition.json",
  "id": "dataset",
  "name": "Dataset",
  "ontologyTermForThisType": {
    "id": "NCIT:C47824",
    "label": "Data set"
  },
~~~
The "name" is a name of Beacon Element of the API which is described by an ontological term ("id" / "label").

IMHO the idea to duplicate OpenAPI via the REST API is too intricate.

Dmitry

**Comment by mbaudis** [comment]
@redmitry Thanks; I understand the use in this example. I was more about why - if the given example is expanding a `basicElement` - this couldn't be

```
{
  "$schema": "../entryTypeDefinition.json",
  "id": "dataset",
  "label": "Dataset",
  "ontologyTermForThisType": {
    "id": "NCIT:C47824",
    "label": "Data set"
  },
```

... but I guess this too much tries to push for some naming alignment which isn't strictly necessary & could become confusing in its own way.
