### ISSUE TITLE
`beaconReceivedRequestSummary` misses `requestParameters` representation

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#53]
The `beaconReceivedRequestSummary` should IMO also represent the request parameters (`requestParameters` from `beaconRequestBody`), not only the `filters`. 

https://github.com/ga4gh-beacon/beacon-framework-v2/blob/e961cabd80711b95b39d0a580cd422928126c9cd/responses/sections/beaconReceivedRequestSummary.json#L15

**Comment by jrambla** [comment]
I truly believe it was there, as the example documents show ;-)
