### ISSUE TITLE
Definition for "iso8601duration" does not exist

### ISSUE THREAD

**Issue by mrueda** [ga4gh-beacon/beacon-framework-v2#56]
Found on 09/03/21 while creating RTD documentation.

**Comment by redmitry** [comment]
Hello Manuel,

**iso8601duration** property is defined in the [age.json](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-draft4-Model/common/age.json) and defined as "string". Note that there is no "duration" format in the [http://json-schema.org/draft-07/schema#](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times). It was added in later drafts. For the draft-7 of schema regex pattern may be added though.

Dmitry

**Comment by mrueda** [comment]
True. All good then.
