### ISSUE TITLE
Naming & repository structure

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#6]
1. framework & model repositories should use similar names (e.g. `beacon-...-v2`)
2. it would be helpful to have them as directories in a single `beacon-v2` or such repository
3. we need an indication of the now deprecated ones and where to find the active projects & branches

A single working repository would also be _immensely_ helpful for keeping issues together...

**Comment by jrambla** [comment]
(Pasting discussion outcomes here to close the issue in an informed way)

1. The rationale behind the  name & versions is: 
a) "Beacon v2" is the name of the domain knowledge we have been describing so far, thus "Beacon v2 Model" should be the natural name of the corresponding model. If "Beacon Model v2" sounds equally clear and it  
b) "Beacon Framework" is the name of the "artifact", hence the version should be appended after the name. We started with "v2" avoid confusions with Beacon v1 and  make this first version number aligned with the model number.

2) Framework and models are kept separated as the Framework could be applied to other domains or scenarios than the Model for Beacon v2
3) The current ones are pinned and the old ones are unpinned. All issues have been solved or moved to the new repos.
