### ISSUE TITLE
entityType vs entryType

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-framework-v2#63]
`requestedSchemas `has the element `entityType`, defined in `SchemasPerEntity `component.
In the whole framework, `entryType `instead of `entity `is being used, it seems that the latter is a remnant of the nomenclature in a previous draft.
Should we update the naming to "`SchemasPerEntryType`" and "`entryType`"? (this will break compliance for existing implementations)

**Comment by jrambla** [comment]
@mbaudis, @Tom-Shorter any comment?

**Comment by mbaudis** [comment]
+1
