### ISSUE TITLE
Documentation for `beaconCollectionsResponse` is missing

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#69]
The current documentation for [Responses](https://github.com/ga4gh-beacon/beacon-framework-v2#the-responses) is missing an entry for the `beaconCollectionsResponse` type. While e.g. the `/datasets` endpoint is discussed as example for "should return the list of all datasets in a Beacon instance", there is no (?) description of this being in the form of a `beaconCollectionsResponse`.

**Comment by mbaudis** [comment]
... see also the related issue in the [verifier](https://github.com/ga4gh-beacon/beacon-verifier/issues/10).

**Comment by laurenfromont** [comment]
@MrRobb let's discuss this
