### ISSUE TITLE
beaconMapSchema.endpointSets => should be singular?

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#7]
`endpointSets` describes set of endpoints, not a _list_ of set**s** of endpoints and should therefore be in singular `endpointSet`, AFAIK.

https://github.com/ga4gh-beacon/beacon-framework-v2/blob/35693fc6994de88b0a3273968e640380a7a1a691/configuration/beaconMapSchema.json#L10

**Comment by jrambla** [comment]
As every root endpointSet could include other sets (endpoints property), we opted for plural. Makes sense?

**Comment by mbaudis** [comment]
Hmmm... not reallyu for the definition here since it describes a single set?

**Comment by mbaudis** [comment]
Ok - closing since plural has been shown since "exampleSet" etc. though probably correct in this context...
