### ISSUE TITLE
schemas response

### ISSUE THREAD

**Issue by carleshf** [ga4gh-beacon/beacon-framework-v2#70]
The folder [responses](https://github.com/ga4gh-beacon/beacon-framework-v2/tree/main/responses) contains the definition for the main responses but I am missing the one for "schemas". I also checked the model and I do not found its definition there neither. Am I missing it or should it be added?

**Comment by jrambla** [comment]
The schemas for the Map, Configuration, etc. could be found in the responses\sections folder.
If you refer to the schemas for entry types like "genomicVariants", they could be found in the respective model repositories.

**Comment by carleshf** [comment]
Thanks Jordi,

From your answer, I assume that I have a legacy endpoint that I have to remove:

` web.get('/api/schemas'          , handler.schemas)`
